# Generated by Django
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('ema20', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='EMA20')),
                ('ema60', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='EMA60')),
                ('ema120', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='EMA120')),
                ('sma20', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='SMA20')),
                ('sma60', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='SMA60')),
                ('sma120', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='SMA120')),
                ('daily_return', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='當日漲跌(%)')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='market_data.stock', verbose_name='股票')),
            ],
            options={
                'verbose_name': '技術指標',
                'verbose_name_plural': '技術指標',
                'unique_together': {('stock', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='indicator',
            index=models.Index(fields=['date'], name='indicator_date_idx'),
        ),
    ]
