# Generated by Django 6.0.5 on 2026-05-07 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorDivergence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('sector_name', models.CharField(max_length=50, verbose_name='族群名稱')),
                ('divergence', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='乖離率(%)')),
                ('is_orange', models.BooleanField(default=False, verbose_name='亮橘燈(連2天前五名)')),
                ('is_pink', models.BooleanField(default=False, verbose_name='亮紫燈(由負轉正)')),
            ],
            options={
                'verbose_name': '族群背離快取',
                'verbose_name_plural': '族群背離快取',
                'indexes': [models.Index(fields=['date'], name='analysis_se_date_234fb4_idx'), models.Index(fields=['sector_name'], name='analysis_se_sector__a5bfa1_idx')],
                'unique_together': {('date', 'sector_name')},
            },
        ),
    ]
