# Generated by Django 6.0.5 on 2026-05-20 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_sectordivergence'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketBreadth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='日期')),
                ('breadth_percent', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='大盤寬度(%)')),
            ],
            options={
                'verbose_name': '大盤寬度',
                'verbose_name_plural': '大盤寬度',
                'ordering': ['-date'],
            },
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='five_day_return',
        ),
    ]
