# Generated by Django 6.0.5 on 2026-05-30 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_marketbreadth_sectordivergence_and_more'),
        ('market_data', '0002_rename_market_data_code_idx_market_data_code_188d00_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='買入日期')),
                ('stock_code', models.CharField(max_length=10, verbose_name='股票代號')),
                ('stock_name', models.CharField(blank=True, max_length=50, verbose_name='股票名稱')),
                ('close', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='收盤價')),
                ('volume', models.BigIntegerField(blank=True, null=True, verbose_name='成交量')),
                ('turnover', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='成交金額(億)')),
                ('ema20', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='EMA20')),
                ('ema60', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='EMA60')),
                ('ema120', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='EMA120')),
                ('signal_type', models.CharField(max_length=10, verbose_name='訊號類型')),
                ('entry_date', models.DateField(verbose_name='入池日期')),
                ('d', models.IntegerField(verbose_name='D值(入池天數)')),
                ('r20', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='R20')),
                ('r20_hole', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='R20_hole')),
                ('scenario', models.CharField(max_length=1, verbose_name='情境')),
                ('market_cap', models.BigIntegerField(blank=True, null=True, verbose_name='市值(元)')),
                ('ema20_cross_date', models.DateField(blank=True, null=True, verbose_name='EMA20穿越日(R欄)')),
                ('first_r_date', models.BooleanField(default=False, verbose_name='首次R日期(S欄)')),
                ('sell_date', models.DateField(blank=True, null=True, verbose_name='賣出日期')),
                ('return_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='報酬率(%)')),
                ('max_drawdown', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='最大回撤(%)')),
                ('max_return_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='最高報酬率(%)')),
                ('scan_run_id', models.CharField(blank=True, help_text='用於辨識同一次掃描 run', max_length=50, verbose_name='掃描批次ID')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buy_pool_entries', to='market_data.stock', verbose_name='股票')),
            ],
            options={
                'verbose_name': '選股掃描結果',
                'verbose_name_plural': '選股掃描結果',
                'indexes': [models.Index(fields=['date'], name='analysis_bu_date_254037_idx'), models.Index(fields=['stock_code'], name='analysis_bu_stock_c_8b1f49_idx'), models.Index(fields=['scan_run_id'], name='analysis_bu_scan_ru_b8cb97_idx')],
                'unique_together': {('date', 'stock_code', 'scan_run_id')},
            },
        ),
    ]
