# Generated by Django 6.0.5 on 2026-05-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_sectordivergence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='five_day_return',
        ),
        migrations.CreateModel(
            name='MarginAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='日期')),
                ('index_close', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='加權指數收盤')),
                ('margin_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='融資金額-資餘(仟元)')),
                ('margin_score', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='融資分數')),
                ('change_1d', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='融資1日變化')),
                ('change_5d', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='融資5日變化')),
                ('change_10d', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='融資10日變化')),
                ('change_20d', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='融資20日變化')),
                ('change_40d', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='融資40日變化')),
                ('score_change_21d', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='融資分數變動率')),
            ],
            options={
                'verbose_name': '融資分析',
                'verbose_name_plural': '融資分析',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['-date'], name='analysis_ma_date_d03b32_idx')],
            },
        ),
    ]
