# Generated by Django 6.0.5 on 2026-05-20 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_marketbreadth_remove_indicator_five_day_return'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='ema120_dev',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='ema20_dev',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='ema60_dev',
        ),
    ]
