# Generated by Django 6.0.5 on 2026-05-06 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='股票代號')),
                ('name', models.CharField(max_length=50, verbose_name='股票名稱')),
                ('market', models.CharField(choices=[('twse', '上市'), ('otc', '上櫃')], max_length=10, verbose_name='市場別')),
                ('market_cap', models.BigIntegerField(blank=True, null=True, verbose_name='市值(元)')),
            ],
            options={
                'verbose_name': '股票',
                'verbose_name_plural': '股票',
                'indexes': [models.Index(fields=['code'], name='market_data_code_188d00_idx'), models.Index(fields=['market'], name='market_data_market_cb82fa_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('open', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='開盤價')),
                ('high', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='最高價')),
                ('low', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='最低價')),
                ('close', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='收盤價')),
                ('volume', models.BigIntegerField(blank=True, null=True, verbose_name='成交股數')),
                ('trade_value', models.BigIntegerField(blank=True, null=True, verbose_name='成交金額(元)')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_prices', to='market_data.stock', verbose_name='股票')),
            ],
            options={
                'verbose_name': '每日股價',
                'verbose_name_plural': '每日股價',
                'ordering': ['-date'],
                'unique_together': {('stock', 'date')},
            },
        ),
    ]
