# Generated by Django 6.0.5 on 2026-05-07 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='outstanding_shares',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='發行股數'),
        ),
    ]
