# Generated by Django 6.0.5 on 2026-05-30 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stock',
            new_name='market_data_code_188d00_idx',
            old_name='market_data_code_idx',
        ),
        migrations.RenameIndex(
            model_name='stock',
            new_name='market_data_market_cb82fa_idx',
            old_name='market_data_market_idx',
        ),
    ]
