# Generated by Django 6.0.5 on 2026-05-14 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0002_stock_outstanding_shares'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='outstanding_shares',
        ),
    ]
