# Generated by Django 6.0.5 on 2026-05-14 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0002_stock_outstanding_shares'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='outstanding_shares',
        ),
        migrations.CreateModel(
            name='StockSharesHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='適用日期')),
                ('outstanding_shares', models.BigIntegerField(blank=True, null=True, verbose_name='發行股數')),
                ('source', models.CharField(default='finmind', max_length=50, verbose_name='資料來源')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares_history', to='market_data.stock', verbose_name='股票')),
            ],
            options={
                'verbose_name': '歷史股數',
                'verbose_name_plural': '歷史股數',
                'ordering': ['-date'],
                'unique_together': {('stock', 'date')},
            },
        ),
    ]
