# Generated by Django 6.0.5 on 2026-05-06 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='留言內容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='留言時間')),
                ('page', models.CharField(default='dashboard', help_text='辨識留言在哪個頁面產生', max_length=50, verbose_name='所在頁面')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='留言者')),
            ],
            options={
                'verbose_name': '留言',
                'verbose_name_plural': '留言',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='加入時間')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_by', to='market_data.stock', verbose_name='追蹤股票')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
            options={
                'verbose_name': '個股追蹤',
                'verbose_name_plural': '個股追蹤',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'stock')},
            },
        ),
    ]
