# Generated by Django 6.0.5 on 2026-05-06 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分類名稱')),
                ('category_type', models.CharField(choices=[('主分類', '主分類'), ('子分類', '子分類')], default='主分類', max_length=20, verbose_name='分類層級')),
            ],
            options={
                'verbose_name': '產業分類',
                'verbose_name_plural': '產業分類',
            },
        ),
        migrations.CreateModel(
            name='StockSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='最後修改時間')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='最後修改者')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks', to='sectors.sector', verbose_name='所屬分類')),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sector_mapping', to='market_data.stock', verbose_name='股票')),
            ],
            options={
                'verbose_name': '股票分類對應',
                'verbose_name_plural': '股票分類對應',
            },
        ),
    ]
